### ISSUE TITLE
Error suggesting apollo-server-express for some reason

### ISSUE THREAD

**Issue by TAnas0** [zapier/apollo-server-integration-testing#4]
Hey,

I have an error trying to use this package. I am trying to setup integration tests on my GraphQL API, especially the context. That's why I found this package of great use.

Problem is when running the following test: `post.module.test.js`

```js
import { createTestClient } from "apollo-server-integration-testing"
import postModule from "../index"
import { ApolloServer } from 'apollo-server'

test('Post Module', async () => {
  const apolloServer = new ApolloServer({
    schema: postModule.schema,
    context: () => {
      return {
      }
    }
  })
  const { query } = createTestClient({apolloServer})

  const res = await query(`{
    whoami {
      fullname
    }
  }`)
  ...
  ...
})

```

... I get this error:
```
> jest --coverage "auth.module"

 FAIL  api/modules/auth/__tests__/auth.module.test.ts
  ✕ Post Module (79ms)

  ● Post Module

    To use Apollo Server with an existing express application, please use apollo-server-express

      27 |   })
      28 |   
    > 29 |   const { query } = createTestClient({apolloServer})
         |                     ^
      30 | 
      31 |   const res = await query(`{
      32 |     whoami {

      at ApolloServer.applyMiddleware (node_modules/apollo-server/src/index.ts:89:11)
      at Object.createTestClient (node_modules/apollo-server-integration-testing/dist/index.js:22:18)
      at api/modules/auth/__tests__/auth.module.test.ts:29:21
      at step (api/modules/auth/__tests__/auth.module.test.ts:33:23)
      at Object.next (api/modules/auth/__tests__/auth.module.test.ts:14:53)
      at api/modules/auth/__tests__/auth.module.test.ts:8:71
      at Object.<anonymous>.__awaiter (api/modules/auth/__tests__/auth.module.test.ts:4:12)
      at Object.<anonymous> (api/modules/auth/__tests__/auth.module.test.ts:8:21)

```

It is worth noting the the `postModule` you see being used is a [GraphQL Module](https://github.com/Urigo/graphql-modules/). The schema passed to the new Apollo Server is valid and have worked for me testing with the standard `apollo-server-testing`.

I don't know why the error message is recommending me to use the Express version, while I am using Apollo Server purely. I do have `express` as a dependency of `apollo-server` for some reason, but I do not use it anywhere in my project.

If the information supplied is not enough and you wish to take a closer look at this, I can set up a reproduction example.

Cheers

EDIT:
This is not the [recommended way to test a GraphQL Module](https://graphql-modules.com/docs/introduction/test-your-module) so it may probably be an issue with Graphql Modules

I've changed my test code and used the `ApolloServer` instance from `apollo-server-express` and managed to "run" my test. It fell back into an old error unrelated to this package.

**Comment by vitorbal** [comment]
@TAnas0 sorry about that! As you discovered, this library will only work with `ApolloServer`s created via `apollo-server-express`.

Since `apollo-server-express` is what we use internally at Zapier, I don't have any plans to add support for other apollo-server setups right now.

Hopefully using `apollo-server-express` is an acceptable solution for you. If not, I'd encourage you to fork this repository and change the logic [here](https://github.com/zapier/apollo-server-integration-testing/blob/f480d3401480ff4516d11da7fd70e1cd63deac32/src/index.ts#L76-L77) and [here](https://github.com/zapier/apollo-server-integration-testing/blob/f480d3401480ff4516d11da7fd70e1cd63deac32/src/index.ts#L109-L112) to work with `apollo-server`.

Apologies again for the hassle. I'll update the README to make sure it's clear we don't support plain `apollo-server` instances.

**Comment by TAnas0** [comment]
No problem at all!

I am still looking around for a good setup for a fresh GraphQL API in Typescript and I may settle on something different, or maybe make the changes if necessary and submit a PR

:+1:
